### ISSUE TITLE
Using `ConfigDict` or `SettingsConfigDict` requires an annotation

### ISSUE THREAD

**Issue by antazoey** [Viicos/flake8-pydantic#14]
When I use other config classes, such as `ConfigDict`, I get flake8 errors with this plugin.
Attempting to annotate those classes leads to mypy complaining about overrides from base model to submodels, and the pydantic documentation doesn't show extra annotation here.

For example, if I have

```python
    model_config = ConfigDict(arbitrary_types_allowed=True)
```

flake8 errors with

```
    PYD002 Non-annotated attribute inside Pydantic model
```

Changing it to 

```python
    model_config: ConfigDict = ConfigDict(arbitrary_types_allowed=True)
```

is not ideal for a few reasons stated above!

**Comment by Viicos** [comment]
Sorry for the delay, fixed in https://github.com/Viicos/flake8-pydantic/pull/16 and in the next published version.
